Models/Order.cs
using System.ComponentModel.DataAnnotations;

namespace FreshGoods.Models
{
    public class Order
    {
        public int Id{get;set;}

         //[Required]
        public ApplicationUser Customer{get;set;}
        //public ApplicationUser UserId{get;set;}

        [Required]
        public decimal TotalPrice{get;set;}
        [Required]
        public decimal Tax{get;set;}
        [Required]
        public decimal FinalPrice{get; set;}
        [Required]
        public bool Paid{get; set;}
        [Required]
        public bool Delivery{get;set;}

        public bool perpared{get; set;}
    }
}

Pages/Admin/Orders/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using FreshGoods.Data;
using FreshGoods.Models;
using System.Text;
using Microsoft.Extensions.Logging;
using MailKit.Net.Smtp;
using MimeKit;
using Microsoft.AspNetCore.Authorization;

namespace FreshGoods.Pages.Admin.Orders
{
    [Authorize(Roles = "Admin,Worker")]
    public class DetailsModel : PageModel
    {
        private readonly FreshGoods.Data.FreshGoodsDbContext _context;
        private readonly ILogger<DetailsModel> _logger;
        public DetailsModel(FreshGoods.Data.FreshGoodsDbContext context, ILogger<DetailsModel> logger)
        {
            _context = context;
            _logger = logger;
        }
        [BindProperty]
        public IList<OrderDetail> OrderDetails { get; set; }
        [BindProperty]
        public Order Order { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Order = await _context.Orders.Include(m => m.Customer).FirstOrDefaultAsync(m => m.Id == id);
            OrderDetails = await _context.OrderDetails.Include(m => m.Item).Where(m => m.Order.Id == id).ToListAsync();

            if (OrderDetails == null|| Order.perpared)
            {
                return NotFound();
            }
            return Page();
        }
        public async Task<IActionResult> OnPostAsync()
        {

            int id = Order.Id;
            Order = await _context.Orders.Include(m => m.Customer).FirstOrDefaultAsync(m => m.Id == id);
            OrderDetails = await _context.OrderDetails.Include(m => m.Item).Where(m => m.Order.Id == id).ToListAsync();
            MimeMessage message = new MimeMessage();

            MailboxAddress from = new MailboxAddress("NoReply",
            "info@freshgoods.com");
            message.From.Add(from);

            MailboxAddress to = new MailboxAddress("",
            Order.Customer.Email);
            message.To.Add(to);
            BodyBuilder mailbody = new BodyBuilder();
            if (Order.Delivery)
            {
                message.Subject = "Delivery is on its way.";
                mailbody.HtmlBody = "<p>Your order has been perpared and is head out for delivery. Delivery include(s):</p>";
            }
            else
            {

                mailbody.HtmlBody = "<p>Your order has been perpared and is Ready for Pick up. Order include(s):</p>";
            }
            mailbody.HtmlBody += "<Table><tr><th>Name</th><th>Amount</th> <th>Price</th></tr>";
            for (int i = 0; i < OrderDetails.Count; i++)
            {
                mailbody.HtmlBody += $"<tr><td>{OrderDetails[i].Item.ItemName}</td><td>{OrderDetails[i].Quantity}</td><td>{OrderDetails[i].Price}</td></tr>";
            }
            mailbody.HtmlBody += $"<tr><td></td><td>Total</td><td>{Order.FinalPrice}</td> </tr>";
            mailbody.HtmlBody += "</Table>";
            message.Subject = $"Order#{Order.Id} has been prepared.";
            message.Body = mailbody.ToMessageBody();
            SmtpClient client = new SmtpClient();
            client.Connect("smtp-relay.sendinblue.com", 465, true);
            client.Authenticate("Kevinparker9908@gmail.com", "W8M9k7GSPApnwr5Q");
            client.Send(message);
            client.Disconnect(true);
            client.Dispose();
            Order.perpared = true;
            _context.Attach(Order).State = EntityState.Modified;
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!OrderExists(Order.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Success");
        }
        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.Id == id);
        }
    }
}

Pages/Admin/Orders/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using FreshGoods.Data;
using FreshGoods.Models;
using Microsoft.AspNetCore.Authorization;

namespace FreshGoods.Pages.Admin.Orders
{
    [Authorize(Roles = "Admin,Worker")]
    public class IndexModel : PageModel
    {
        private readonly FreshGoods.Data.FreshGoodsDbContext _context;

        public IndexModel(FreshGoods.Data.FreshGoodsDbContext context)
        {
            _context = context;
        }

        public IList<Order> Order { get;set; }

        public async Task OnGetAsync()
        {
            Order = await _context.Orders.Where(m=>m.perpared==false).ToListAsync();
        }
    }
}

Pages/Admin/Orders/Success.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FreshGoods.Pages.Admin.Orders
{
    [Authorize(Roles = "Admin,Worker")]
    public class SuccessModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/BuyItem.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using FreshGoods.Models;
using FreshGoods.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FreshGoods.Pages
{
    public class BuyItemModel : PageModel
    {
        private readonly FreshGoodsDbContext db;  
        public BuyItemModel(FreshGoodsDbContext db) => this.db = db;
       
        public List<Item> Items ;
        public string ReturnUrl { get; set; }
        public void OnGet()
        {
            //ProductModel prodModel = new ProductModel();
            //Items = prodModel.findAll();
            Items = db.Items.ToList();
        }


    }
}

Pages/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using FreshGoods.Helpers;
using FreshGoods.Models;
using FreshGoods.Data;
using Microsoft.AspNetCore.Authorization;

namespace FreshGoods.Pages
{
    [Authorize]
    public class CartModel : PageModel
    {
        private readonly FreshGoodsDbContext db;  
        public CartModel(FreshGoodsDbContext db) => this.db = db;
        public List<Item>  Items {get;set;} = new List<Item>();
        public List<ItemCart> cart {get; set;}
        public decimal Total {get; set;}
        public void OnGet()
        {
            cart = SessionHelper.GetObjectFromJson<List<ItemCart>>(HttpContext.Session,"cart");
            Total = cart.Sum(i => i.Item.Price * i.CartQuantity);    
        }
        
        public IActionResult OnGetBuyNow(int id){
           // var prodModal = new ProductModel();
            cart = SessionHelper.GetObjectFromJson<List<ItemCart>>(HttpContext.Session, "cart");
            if (cart == null)
            {
                cart = new List<ItemCart>();
                cart.Add(new ItemCart
                {
                    //Item = prodModal.find(id),
                    Item = find(id),
                    CartQuantity = 1
                });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                int index = Exists(cart, id);
                if (index == -1)
                {
                    cart.Add(new ItemCart
                    {
                        //Item = prodModal.find(id),
                        Item = this.find(id),
                        CartQuantity = 1
                    });
                }
                else
                {
                    cart[index].CartQuantity++;
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToPage("Cart");
        }
    public IActionResult OnGetDelete(int id)
        {
            cart = SessionHelper.GetObjectFromJson<List<ItemCart>>(HttpContext.Session, "cart");
            int index = Exists(cart, id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToPage("Cart");
        }

        public IActionResult OnPostUpdate(int[] quantities)
        {
            cart = SessionHelper.GetObjectFromJson<List<ItemCart>>(HttpContext.Session, "cart");
            for (var i = 0; i < cart.Count; i++)
            {
                cart[i].CartQuantity = quantities[i];
            }
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToPage("Cart");
        }

        private int Exists(List<ItemCart> cart, int id)
        {
            for (var i = 0; i < cart.Count; i++)
            {
                if (cart[i].Item.Id == id)
                {
                    return i;
                }
            }
            return -1;
        }
    
        public Item find(int id){
            Items = db.Items.ToList();
            return Items.Where(p => p.Id == id).FirstOrDefault();
        }
    }
}

Pages/Category.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using FreshGoods.Data;
using FreshGoods.Models;

namespace FreshGoods.Pages
{
    public class CategoryModel : PageModel
    {
        public List<Item> Items { get; set; } = new List<Item>();
        public List<ItemCategory> ItemCategories { get; set; } = new List<ItemCategory>();

        [BindProperty(SupportsGet = true)]
        public string Slug { get; set; }

        public String CategoryName { get; set; }
        private readonly FreshGoodsDbContext db;
        private readonly ILogger<IndexModel> _logger;
        public CategoryModel(FreshGoodsDbContext db, ILogger<IndexModel> logger)
        {
            this.db = db;
            _logger = logger;
        }

        public async Task OnGetAsync()
        {
            ItemCategories = await db.ItemCategories.ToListAsync();

            Items = await db.Items.ToListAsync();

            if (Slug != null) {
                ItemCategory selectedCategory = ItemCategories.FirstOrDefault(p => p.Slug == Slug);
                Items = Items.Where(item => item.CategoryId == selectedCategory.Id).ToList();
            }
        }
    }
}

Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace FreshGoods.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using FreshGoods.Data;
using FreshGoods.Models;

namespace FreshGoods.Pages
{
    public class IndexModel : PageModel
    {
        public List<Item> Items { get; set; } = new List<Item>();

        private readonly FreshGoodsDbContext db;
        private readonly ILogger<IndexModel> _logger;
        public IndexModel(FreshGoodsDbContext db, ILogger<IndexModel> logger)
                {
                    this.db = db;
                    _logger = logger;
                }

        public async Task OnGetAsync()
        {
            Items = await db.Items.Take(4).ToListAsync(); // take only the 4 first items of db
        }
    }
}

Pages/OrderSuccess.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FreshGoods.Pages
{
    public class OrderSuccessModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace FreshGoods.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/BuyItem.cshtml
@page
@model FreshGoods.Pages.BuyItemModel
@{
    ViewData["Title"]="Add Product";
}
    
<html>
    <head>
        <meta name="viewport" content="width=device-width">
        <tittle>Buy Items</tittle>
        <style>
            .td-data{
                width:100px;
                text-align:center;
                align-item:center;
            }
            .img-size{
                width:250px;
                height: 130px;
            }
        </style>
    </head>
    <body>
        <h3>Product List</h3>
        <table border="1">
            <tr class="td-data">
                <th>No</th>
                <th>Item Name</th>
                <th>Photo</th>
                <th>Item Price</th>
                <th>Action</th>
            </tr>
            @foreach (var item in Model.Items)
            {
                <tr class="td-data">
                    <td class="td-data">@item.Id</td>
                    <td class="td-data">@item.ItemName</td>
                    <td><img src="~/images/@item.ImagePath" class="img-size"></td>
                    <td class="td-data">@item.Price</td>
                    <td class="td-data">
                        <a asp-page="cart" asp-page-handler="buynow" asp-route-id="@item.Id">Buy Now</a>
                    </td>
                </tr>
            }
        </table>
    </body>
</html>

Pages/Cart.cshtml
@page
@model FreshGoods.Pages.CartModel
@{
    ViewData["Title"] = "My Cart";
}

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css"
    integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cart Item</title>
    <style>
        .item-qty {
            width: 100px;
            text-align: center;
        }

        .img-size {
            width: 40%;
        }

        .cart-item-row {
            border-bottom: 2px solid black;
        }
    </style>
</head>

<body>
    <h2 class="text-center p-4 our-prod-title">My Cart</h2>
    <form method="post" asp-page="cart" asp-page-handler="update">
        <div class="row border border-success" >

            <div class="col-md-1 font-weight-bold text-center">Id</div>
            <div class="col-md-2 font-weight-bold text-center">Name</div>
            <div class="col-md-2 font-weight-bold text-center">Photo</div>
            <div class="col-md-1 font-weight-bold text-center">Price</div>
            <div class="col-md-1 font-weight-bold text-center">Unit</div>
            <div class="col-md-2 font-weight-bold text-center">Quantity <br><input type="submit" value="Update"
                    class="btn btn-success" /></div>
            <div class="col-md-1 font-weight-bold text-center">Action</div>
            <div class="col-md-2 font-weight-bold text-center">Sub Total</div>
        </div>
        @foreach (var item in Model.cart)
        {
            <div class="row cart-item-row py-3 border border-success">
                <div class="td-data col-md-1 align-self-center text-center">@item.Item.Id</div>
                <div class="td-data col-md-2 align-self-center text-center">@item.Item.ItemName</div>
                <div class="col-md-2 align-self-center text-center"><img src="~/images/@item.Item.ImagePath"
                    style="width:8rem;" /></div>
                <div class="td-data col-md-1 align-self-center text-center">$@item.Item.Price</div>
                <div class="td-data col-md-1 align-self-center text-center">@item.Item.Unit</div>
                <div class="col-md-2 align-self-center text-center"><input type="number" name="quantities"
                    value="@item.CartQuantity" min="1" class="item-qty" />
                </div>
                <div class="td-data col-md-1 align-self-center text-center">
                    <a asp-page="cart" asp-page-handler="delete" asp-route-id="@item.Item.Id"><i
                        class="fas fa-trash-alt"></i></a>
                </div>
                <div class="td-data col-md-2 align-self-center text-center">
                    $@(item.Item.Price * item.CartQuantity)
                </div>
            </div>
        }
    </form>
    <div class="d-flex flex-row justify-content-end py-3">
        <div>
            <h6 class="mr-5">Total</h6>
        </div>
        <div class="mr-5">&nbsp;&nbsp;</div>
        <div class="mr-5">
            <h6>$@Model.Total</h6>
        </div>
    </div>
    <div class="d-flex flex-row justify-content-between py-3">
        <div><a asp-page="Category" class="btn btn-success"> <i class="fas fa-arrow-left"> </i> Continue Shopping</a>
        </div>
        <div>
            @if (@Model.User.Identity.IsAuthenticated)
            {
                <a asp-page="Order" class="btn btn-success">Proceed to Payment <i class="fas fa-arrow-right"> </i></a>
            }
            else
            {
                <a asp-page="Account/Login" class="btn btn-success">Proceed to Payment <i class="fas fa-arrow-right">
                    </i></a>
            }
        </div>
    </div>
    @* ------------ JS Bootstrap ------------- *@
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

Pages/Category.cshtml
@page "{slug?}"
@model FreshGoods.Pages.CategoryModel
@{
    ViewData["Title"] = "Product Category";
}

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css"
    integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">

<body>
    <div class="main-content">

        <div>
            <h2 class="text-center p-4 our-prod-title">Our Products</h2>
        </div>

        <!----------------------- start category buttons -------------------------->
        <div class="d-flex flex-row justify-content-between">
            <a asp-page="/Category" asp-route-slug="" class="@((Model.Slug==null) ? "btn btn-outline-success active" : "btn btn-outline-success")">View All</a>
            @foreach (var category in Model.ItemCategories)
            {
                <a asp-page="/Category" asp-route-slug="@category.Slug" class="@(Model.Slug == @category.Slug ? "btn btn-outline-success active" : "btn btn-outline-success")">@category.CategoryName</a>
                
            }
        </div>
        <!----------------------- end category buttons -------------------------->

        <!----------------------- start random cards -------------------------->
        <section class="services ">

            <div class="section-center d-flex justify-content-between row">
                <!-- single card 1 -->
                @foreach (var item in Model.Items)
                {
                    <div class="service-card">
                        <div class="service-img-container">
                            <img src="~/Images/@item.ImagePath" class="service-img" alt="single service" />
                            <span class="service-icon">
                                @if (@item.CategoryId == 1)
                                {
                                    <i class="fas fa-lemon card-icon"></i>
                                }
                                @if (@item.CategoryId == 2)
                                {
                                    <i class="fas fa-drumstick-bite card-icon"></i>
                                }
                                @if (@item.CategoryId == 3)
                                {
                                    <i class="fas fa-carrot card-icon"></i>
                                }
                                @if (@item.CategoryId == 4)
                                {
                                    <i class="fas fa-bread-slice card-icon"></i>
                                }
                            </span>
                        </div>
                        <div class="service-info">
                            <h5>@item.ItemName </h5>
                            <p>
                                $ @item.Price <span>@item.Unit</span>
                            </p>
                            <div class="col-auto mt-3">
                                <a class="btn btn-success" asp-page="cart" asp-page-handler="buynow"
                                asp-route-id="@item.Id">Buy Item</a>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </section>
        @* <!----------------------- end of random cards --------------------------> *@

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>

</body>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css"
    integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">

<body>
    <div class="main-content">

        <!----------------------- start carrousel -------------------------->
        <div class="carrousel-deals">
            <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="./images/car-1.jpeg" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                            <h5 class="h5-carousel">Order your fresh food online conveniently delivered to your home
                            </h5>
                            @* <p>You can buy local and that's kind of same thing</p> *@

                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="./images/car-6.jpeg" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                            <h5 class="h5-carousel">We are committed to provide you with fresh fruits and vegetables
                                available at all times</h5>
                            @* <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p> *@
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="./images/car-4.jpeg" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                            <h5 class="h5-carousel">A diversity of fruits, vegetables, meat and bakery products</h5>
                            @* <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p> *@
                        </div>

                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

        </div>
        <!----------------------- end carrousel -------------------------->
        <div>
            <h2 class="text-center featured-title">Featured products</h2>
        </div>

        <!----------------------- start random cards -------------------------->
        <section class="services">

            <div class="section-center d-flex justify-content-between row">
                <!-- single card 1 -->
                @foreach (var item in Model.Items)
                {
                    <article class="service-card ">
                        <div class="service-img-container">
                            <img src="~/Images/@item.ImagePath" class="service-img" alt="single service" />
                            <span class="service-icon">
                                @if (@item.CategoryId == 1)
                                {
                                    <i class="fas fa-lemon card-icon"></i>
                                }
                                @if (@item.CategoryId == 2)
                                {
                                    <i class="fas fa-drumstick-bite card-icon"></i>
                                }
                                @if (@item.CategoryId == 3)
                                {
                                    <i class="fas fa-carrot card-icon"></i>
                                }
                                @if (@item.CategoryId == 4)
                                {
                                    <i class="fas fa-bread-slice card-icon"></i>
                                }
                            </span>
                        </div>
                        <div class="service-info">
                            <h5>@item.ItemName </h5>
                            <p>
                                $ @item.Price <span>@item.Unit</span>
                            </p>
                            <div class="col-auto mt-3">
                                <a class="btn btn-success" asp-page="cart" asp-page-handler="buynow"
                                asp-route-id="@item.Id">Buy Item</a>
                            </div>
                        </div>
                    </article>
                }

            </div>
        </section>
        @* <!----------------------- End of random cards --------------------------> *@

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
</body>

Pages/OrderSuccess.cshtml
@page
@model FreshGoods.Pages.OrderSuccessModel
@{
    ViewData["Title"] = "Order Success";
}
<h1>@ViewData["Title"]</h1>
@{
    <p>We receiver your Order. 
        <a class="nav-link" asp-area="" asp-page="/Categoty">Click here to Buy .</a>
    </p>
}